name: qgtagger_training
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pytorch-lightning
  - scikit-learn
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - tqdm
  - pyarrow 
  - pip
