name: qgtagger_training
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1  # GPU 支援
  - scikit-learn
  - uproot
  - awkward
  - numba
  - matplotlib
  - pyyaml
  - pyarrow
  - pandas

